#!/bin/bash

# Core Bootloader Setup for stable branch

bootloader_setup() {
    PrintHeader "Bootloader Setup"

    if [[ "$DUAL_BOOT_MODE" == "gpt" ]]; then
        PrintStatus "Installing GRUB for dual-boot"
        pacstrap /mnt grub efibootmgr os-prober || HandleFatalError "Failed to install GRUB"
        arch-chroot /mnt os-prober || true
        arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=Arch || HandleFatalError "grub-install failed"
        arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg || HandleFatalError "grub-mkconfig failed"
    else
        PrintStatus "Installing systemd-boot"
        pacstrap /mnt systemd-bootctl || true
        arch-chroot /mnt bootctl install || HandleFatalError "bootctl install failed"
        # Kernel entries will be generated by mkinitcpio + kernel install; ensure preset exists
        PrintStatus "systemd-boot installed"
        if [[ "$ENABLE_SECURE_BOOT" == "true" ]]; then
            PrintWarning "Secure Boot signing is deferred on stable core. System boots unsigned kernel; signing can be added later."
        fi
    fi
}
